runtime: python27
threadsafe: yes
api_version: 1

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest


handlers:
- url: /static
  static_dir: static  
- url: .*
  script: main.app
  secure: always
